name: calendar
description: Calendar app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # SVG 사용 위해...
  flutter_svg: ^1.1.5

  # Swiper 사용 위해...
  carousel_slider: ^4.1.1

  # mapIndexed() 등의 도구들 사용 위해...
  collection: ^1.16.0

  # 상태 관리를 위해...
  provider: ^6.0.4

  # DateFormat 기능을 위해...
  intl: ^0.17.0

  # freezed를 위한 annotation이 들어있는 패키지
  freezed_annotation: ^2.2.0

  #json_serializable를 위한 annotation이 들어있는 패키지
  json_annotation: ^4.7.0

  # Widget이 viewport 안에 있는지 체크를 위해...
  visibility_detector: ^0.3.3

  # DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  # DI
  get_it: ^7.2.0
  injectable: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # data-class 생성과 immutable을 위한 패키지
  freezed: ^2.1.1

  # freezed로 fromJson/toJson 생성을 하게 하기 위한 패키지
  json_serializable: ^6.5.4

  # Dart 코드 생성 도구
  hive_generator: ^1.1.3
  build_runner: ^2.2.1
  injectable_generator: ^1.5.4

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
